#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
. ~/Dropbox/z/z/z/z.sh

export PATH="/home/serge/bin:/home/serge/anaconda3/bin:$PATH"
